'use strict';

const D = Math.PI / 180;
const configs = {
  1:['Angles and Turns','See an angle as part of one complete rotation.','circle',[['Angle','angle',0,720,5,90]],v=>[['Turns',v.angle/360],['Quarter turns',v.angle/90]]],
  2:['Degrees and Radians','Compare the two common ways to measure an angle.','circle',[['Degrees','angle',0,360,5,180]],v=>[['Radians',v.angle*D],['In terms of π',`${fmt(v.angle/180)}π`]]],
  3:['Right Triangles','Change the legs and watch the hypotenuse respond.','triangle',[['Width','a',1,12,.5,6],['Height','b',1,12,.5,8]],v=>[['Hypotenuse',Math.hypot(v.a,v.b)],['Acute angle',`${fmt(Math.atan2(v.b,v.a)/D)}°`]]],
  4:['Similar Triangles','Scaling a triangle changes its size, not its angles.','triangle',[['Scale','scale',.5,3,.1,1],['Angle','angle',15,75,1,35]],v=>[['Base',5*v.scale],['Height',5*v.scale*Math.tan(v.angle*D)],['Angle',`${v.angle}°`]]],
  5:['Sine as a Ratio','Sine compares the opposite side with the hypotenuse.','triangle',[['Angle','angle',5,85,1,30],['Hypotenuse','hyp',2,15,.5,10]],v=>[['Opposite',v.hyp*Math.sin(v.angle*D)],['sin(angle)',Math.sin(v.angle*D)]]],
  6:['Cosine as a Ratio','Cosine compares the adjacent side with the hypotenuse.','triangle',[['Angle','angle',5,85,1,40],['Hypotenuse','hyp',2,15,.5,10]],v=>[['Adjacent',v.hyp*Math.cos(v.angle*D)],['cos(angle)',Math.cos(v.angle*D)]]],
  7:['Tangent as a Ratio','Tangent compares the opposite and adjacent sides.','triangle',[['Angle','angle',5,80,1,45],['Adjacent','adj',2,15,.5,8]],v=>[['Opposite',v.adj*Math.tan(v.angle*D)],['tan(angle)',Math.tan(v.angle*D)]]],
  8:['SOH–CAH–TOA','Explore all three trig ratios in one right triangle.','triangle',[['Angle','angle',5,85,1,35],['Hypotenuse','hyp',2,15,.5,10]],v=>[['sin = O/H',Math.sin(v.angle*D)],['cos = A/H',Math.cos(v.angle*D)],['tan = O/A',Math.tan(v.angle*D)]]],
  9:['Finding a Missing Side','Use sine to reveal an unknown opposite side.','triangle',[['Angle','angle',5,85,1,30],['Hypotenuse','hyp',2,15,.5,10]],v=>[['Opposite',v.hyp*Math.sin(v.angle*D)],['Rule','H × sin(θ)']]],
 10:['Inverse Sine','Recover an angle from opposite ÷ hypotenuse.','triangle',[['Opposite','opp',1,9,.5,5],['Hypotenuse','hyp',10,15,.5,10]],v=>[['Angle',`${fmt(Math.asin(Math.min(v.opp/v.hyp,1))/D)}°`],['Ratio',v.opp/v.hyp]]],
 11:['Inverse Cosine','Recover an angle from adjacent ÷ hypotenuse.','triangle',[['Adjacent','adj',1,9,.5,7],['Hypotenuse','hyp',10,15,.5,10]],v=>[['Angle',`${fmt(Math.acos(Math.min(v.adj/v.hyp,1))/D)}°`],['Ratio',v.adj/v.hyp]]],
 12:['Inverse Tangent','Recover an angle from opposite ÷ adjacent.','triangle',[['Opposite','opp',1,12,.5,6],['Adjacent','adj',1,12,.5,8]],v=>[['Angle',`${fmt(Math.atan2(v.opp,v.adj)/D)}°`],['Ratio',v.opp/v.adj]]],
 13:['Angle of Elevation','Aim upward from a horizontal sight line.','triangle',[['Distance','adj',2,30,1,12],['Height','opp',1,20,1,8]],v=>[['Elevation',`${fmt(Math.atan2(v.opp,v.adj)/D)}°`],['Line of sight',Math.hypot(v.opp,v.adj)]]],
 14:['Angle of Depression','Look downward from a horizontal sight line.','depression',[['Distance','adj',2,30,1,14],['Height','opp',1,20,1,7]],v=>[['Depression',`${fmt(Math.atan2(v.opp,v.adj)/D)}°`],['Line of sight',Math.hypot(v.opp,v.adj)]]],
 15:['The Unit Circle','Connect an angle to its cosine and sine coordinates.','circle',[['Angle','angle',0,360,1,60]],v=>[['cos θ (x)',Math.cos(v.angle*D)],['sin θ (y)',Math.sin(v.angle*D)],['Radius',1]]],
 16:['Quadrants and Signs','Watch sine and cosine signs change by quadrant.','circle',[['Angle','angle',0,360,1,135]],v=>[['Quadrant',Math.floor((v.angle%360)/90)+1],['cos sign',Math.cos(v.angle*D)>=0?'+':'−'],['sin sign',Math.sin(v.angle*D)>=0?'+':'−']]],
 17:['Reference Angles','Find the acute angle to the nearest x-axis.','circle',[['Angle','angle',0,360,1,220]],v=>[['Reference angle',`${fmt(ref(v.angle))}°`],['Quadrant',Math.floor((v.angle%360)/90)+1]]],
 18:['Special Angle Values','Explore exact-angle landmarks on the unit circle.','circle',[['Angle','angle',0,360,15,45]],v=>[['cos θ',Math.cos(v.angle*D)],['sin θ',Math.sin(v.angle*D)]]],
 19:['The Pythagorean Identity','See cos²θ + sin²θ remain equal to one.','circle',[['Angle','angle',0,360,1,55]],v=>[['cos² θ',Math.cos(v.angle*D)**2],['sin² θ',Math.sin(v.angle*D)**2],['Sum',1]]],
 20:['Complementary Angles','Compare sine of θ with cosine of 90° − θ.','triangle',[['Angle','angle',0,90,1,30]],v=>[['sin θ',Math.sin(v.angle*D)],['cos(90°−θ)',Math.cos((90-v.angle)*D)],['Complement',`${90-v.angle}°`]]],
 21:['The Sine Wave','Unwrap vertical motion around a circle into a wave.','wave',[['Angle','angle',0,720,1,180]],v=>[['sin θ',Math.sin(v.angle*D)],['Cycle',Math.floor(v.angle/360)+1]]],
 22:['The Cosine Wave','Trace horizontal circle motion as a wave.','wave',[['Angle','angle',0,720,1,90],['Phase','phase',0,90,90,90]],v=>[['cos θ',Math.cos(v.angle*D)],['Lead over sine','90°']]],
 23:['Amplitude','Stretch or shrink a wave vertically.','wave',[['Amplitude','amp',.25,3,.05,1.5],['Angle','angle',0,720,1,240]],v=>[['Value',v.amp*Math.sin(v.angle*D)],['Range',`−${v.amp} to ${v.amp}`]]],
 24:['Period','Control how quickly a wave repeats.','wave',[['Coefficient','freq',.5,3,.25,2],['Angle','angle',0,720,1,180]],v=>[['Value',Math.sin(v.freq*v.angle*D)],['Period',`${fmt(360/v.freq)}°`]]],
 25:['Phase Shift','Slide a wave left or right.','wave',[['Shift','shift',-180,180,5,60],['Angle','angle',0,360,1,180]],v=>[['Value',Math.sin((v.angle-v.shift)*D)],['Form',`sin(θ − ${v.shift}°)`]]],
 26:['Vertical Shift','Move a wave’s center line up or down.','wave',[['Shift','vertical',-2,2,.1,.5],['Angle','angle',0,360,1,180]],v=>[['Value',Math.sin(v.angle*D)+v.vertical],['Midline',`y = ${v.vertical}`]]],
 27:['Law of Sines','Relate each side to the sine of its opposite angle.','oblique',[['Angle A','angle',20,70,1,50],['Angle B','angle2',20,70,1,60],['Side a','side',2,12,.5,8]],v=>[['Angle C',`${180-v.angle-v.angle2}°`],['Side b',v.side*Math.sin(v.angle2*D)/Math.sin(v.angle*D)]]],
 28:['Law of Cosines','Find the third side when two sides and their angle are known.','oblique',[['Side a','a',2,15,.5,8],['Side b','b',2,15,.5,10],['Included angle','angle',10,160,1,60]],v=>[['Side c',Math.sqrt(v.a*v.a+v.b*v.b-2*v.a*v.b*Math.cos(v.angle*D))],['Rule','c² = a² + b² − 2ab cos C']]],
 29:['Triangle Area with Sine','See how the included angle controls triangle area.','oblique',[['Side a','a',2,15,.5,8],['Side b','b',2,15,.5,10],['Included angle','angle',0,180,1,60]],v=>[['Area',.5*v.a*v.b*Math.sin(v.angle*D)],['Rule','½ab sin C']]],
 30:['Bearings','Measure clockwise from north and split a trip into components.','bearing',[['Bearing','angle',0,360,1,30],['Distance','distance',1,20,.5,10]],v=>[['East',v.distance*Math.sin(v.angle*D)],['North',v.distance*Math.cos(v.angle*D)]]]
};

function fmt(n){ return Number.isFinite(+n) ? (+n).toFixed(3).replace(/\.000$/,'').replace(/(\.\d*?)0+$/,'$1') : n; }
function ref(a){ a=((a%360)+360)%360; return a<=90?a:a<=180?180-a:a<=270?a-180:360-a; }
const id=Number(document.body.dataset.lab), c=configs[id], values={};
document.title=`Lab ${id}: ${c[0]}`; document.querySelector('h1').textContent=c[0]; document.querySelector('.idea').textContent=c[1];
const controls=document.querySelector('.controls');
c[3].forEach(([label,key,min,max,step,value])=>{values[key]=value; const el=document.createElement('label'); el.innerHTML=`${label}<span class="control-row"><input aria-label="${label}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"><output>${value}</output></span>`; const input=el.querySelector('input'),out=el.querySelector('output'); input.addEventListener('input',()=>{values[key]=+input.value;out.textContent=fmt(values[key]);render()}); controls.append(el)});
const canvas=document.querySelector('canvas'), ctx=canvas.getContext('2d');
function render(){const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight; if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);draw(c[2],w,h);document.querySelector('.results').innerHTML=c[4](values).map(([k,v])=>`<div class="result"><span>${k}</span><strong>${typeof v==='number'?fmt(v):v}</strong></div>`).join('');}
function line(x1,y1,x2,y2,color='#5de4f2',width=3){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function draw(type,w,h){ctx.fillStyle='#a9b9d4';ctx.font='14px system-ui'; if(type==='wave')return wave(w,h); if(type==='circle'||type==='bearing')return circle(w,h,type); const pad=55,base=w-pad*2,height=h-pad*2, ang=(values.angle??Math.atan2(values.opp||values.b||6,values.adj||values.a||8)/D)*D; let x1=pad,y1=h-pad,x2=w-pad,y2=y1,x3=x2,y3=Math.max(pad,y1-Math.tan(Math.min(ang,1.35))*base*.55); if(type==='depression'){y1=pad;y2=pad;x3=x2;y3=h-pad} if(type==='oblique'){x3=pad+base*.48;y3=pad} line(x1,y1,x2,y2,'#ffd166');line(x2,y2,x3,y3,'#ff7aa2');line(x3,y3,x1,y1);ctx.fillText(type==='depression'?'horizontal sight line':'adjacent / base',pad,y1+22);ctx.fillText('opposite / height',x2-5,(y2+y3)/2);}
function circle(w,h,type){const r=Math.min(w,h)*.31,cx=w/2,cy=h/2,a=(values.angle||0)*D-Math.PI/2;line(cx-r-25,cy,cx+r+25,cy,'#263a5d',1);line(cx,cy-r-25,cx,cy+r+25,'#263a5d',1);ctx.strokeStyle='#5de4f2';ctx.lineWidth=3;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();const px=cx+r*Math.cos(a),py=cy+r*Math.sin(a);line(cx,cy,px,py,'#ffd166',4);ctx.fillStyle='#ff7aa2';ctx.beginPath();ctx.arc(px,py,7,0,7);ctx.fill();ctx.fillStyle='#a9b9d4';ctx.fillText(type==='bearing'?'N':'0°',cx+5,cy-r-8); if(type==='bearing'){ctx.fillText('E',cx+r+10,cy+5);ctx.fillText('S',cx-5,cy+r+18);ctx.fillText('W',cx-r-22,cy+5)}}
function wave(w,h){const mid=h/2,pad=35,scale=Math.min(h*.18,55),freq=values.freq||1,shift=values.shift||0;line(pad,mid,w-pad,mid,'#263a5d',1);ctx.strokeStyle='#5de4f2';ctx.lineWidth=3;ctx.beginPath();for(let x=pad;x<=w-pad;x++){const deg=(x-pad)/(w-pad*2)*720,cosine=id===22;const val=cosine?Math.cos(deg*D):(values.amp||1)*Math.sin((freq*deg-shift)*D)+(values.vertical||0);const y=mid-scale*val;x===pad?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke();const deg=values.angle||0,x=pad+(deg/720)*(w-pad*2),val=id===22?Math.cos(deg*D):(values.amp||1)*Math.sin((freq*deg-shift)*D)+(values.vertical||0);ctx.fillStyle='#ff7aa2';ctx.beginPath();ctx.arc(x,mid-scale*val,7,0,7);ctx.fill()}
render(); addEventListener('resize',render);
